In [4]:
import numpy as np

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as sri

In [6]:
a=np.array([1,2,3])

In [7]:
print(a)

[1 2 3]


In [10]:
c=np.array([(1,2,3),(4,5,6)])

In [11]:
print(c)

[[1 2 3]
 [4 5 6]]


In [12]:
trans=np.transpose(c)

In [13]:
print(trans)

[[1 4]
 [2 5]
 [3 6]]


In [15]:
trans.ravel()

array([1, 4, 2, 5, 3, 6])

In [19]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [22]:
ze=np.zeros((4,4))

In [23]:
print(ze)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
one=np.ones((3,3))

In [25]:
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
np.random.random((4,4))

array([[0.68908058, 0.92536065, 0.51633678, 0.77201463],
       [0.35603661, 0.6499037 , 0.70887982, 0.4638501 ],
       [0.14370717, 0.88192084, 0.4118636 , 0.49127045],
       [0.17085422, 0.17272654, 0.30873994, 0.3236705 ]])